---
title: "Lab 9: Correlation and Introduction to Simple Linear Regression"
author: "NAME"
format: html
embed-resources: true
html-math-method: mathml
execute:
  warning: false
  echo: true
  error: false
---


## Before you start:

1. Complete the Lab Primer linked in Canvas.  
2. Be sure you have opened the `lab9-intro-two-quant-student.Rproj` file.  
3. Change the name of the **QMD** file only to your last name, first initial, e.g., `OtterM-lab9-intro-two-quant-student.qmd`. You will have to close the QMD document to rename the file. 
4. Change the "NAME" above after `author:` to your name, leaving it in quotes: "Monte Otter" 


## Skills
* Given a study, distinguish between explanatory and response variables
* Given a set of raw data, make a scatterplot or regression output using R
* Given a set of raw data, be able to calculate correlation
* Be able to use correlation to identify the strength and direction of a linear association
* Given a scatterplot, identify patterns such as positive and negative associations
* Given standard regression output, identify and utilize key parts of the output (estimated slope, intercept)

These skills incorporate LTs 17 and R LTs R8, R9, and R10.


*Tip: putting two spaces after a line forces the next line in your Quarto document to also be a new line in your knitted document.*

*Tip: equations in will ignore any attempt to include spaces, unless you insert a `~` inside the equation where you want the space.* For example, in our BAC-Beers problem from class (hover your mouse over each formula to see what it would knit like): $x_{number of beers}$ versus $x_{number~of~beers}$

*Tip: If you want to test out two lines of code, such as for a plot (such as you've seen previously with piped functions), you have to run them **together**, not one at a time.*

Here are some symbols that you might find useful: 

$\hat{y}$

$\hat{y}_{word}$  

$x_{word}$  

$\beta_{word}$  


**Reminder:** Before you start the lab, add the code that will load any other packages you might need into this code chunk.

```{r}
#| label: setup
#| include: false
library(tidyverse)


```

## Scenario 1: Brain Weight in Healthy Adults  

A study published in 1905 had the goal of predicting the approximate weight of the human brain in healthy adults and theorized that the size of the head would be a good predictor. The researchers at Middlesex teaching Hospital decided to focus on post-mortem patients who had suffered accidental deaths, as a reasonable way to collect the data for the population of healthy adults. Over the period of three years, they randomly selected post-mortem patients and for each case, measured first the head size (cm^3^) and then took out the brain and weighed it (in grams). The researchers defined the size of the head as the product of the three principal diameters of the head. Additionally, the patients’ sex (male or female) and age group (20-46 or 46+) was recorded. The data is in `brain-head.csv`.  
*Source: R.J. Gladstone (1905). "A Study of the Relations of the Brain to to the Size of the Head", Biometrika, Vol. 4, pp105-123*


### 1.1.

Name the response and explanatory variables of interest and, for each, state the type of variable (quantitative or qualitative).

> Response:

> Explanatory:


### 1.2.

What type of study is this (observational or experimental)? Justify your answer in the context of the study.

> Insert answer here  


### 1.3.

Exploratory Data Analysis: Insert a code chunk below to create an appropriate graphic and calculate any appropriate summary statistics. Modify the plot so that the y axis spans from 900 to 1800 grams.  

< Insert code chunk here >  


### 1.4.

What is the simplest form (linear, nonlinear, etc) of the relationship between the brain weight and head size of healthy adults?

> Insert answer here  


### 1.5.

What is the strength and direction of the linear relationship? Cite your evidence. (You may want to refer to 1.3 / use your best evidence)

> Insert answer here  


### 1.6.

Create a scatterplot of the data, including both the axis modification and the estimated linear model on the plot.

< Insert code chunk here >  


### 1.7.

Create your linear model. Then, write the code below to print out the coefficients for your estimates of slope and intercept of your linear model between between the brain weight and head size and write them below.

< Insert code chunk here >  

> $b_0$ = 

> $b_1$ = 


### 1.8.

Write the equation for your estimate of the linear model between brain weight and head size. Use the appropriate formatting for symbols.

> Insert answer here  


### 1.9.

Interpret the slope of the linear model, in context.

> Insert answer here  


### 1.10.

First interpret the intercept of the linear model, in context (provide the mathematical interpretation, whether it makes sense or not practically). Then, explain whether this interpretation is practical.

> Insert answer here  


### 1.11.

What is the average brain size for a healthy adult with a head size of 3421 cm^3^? Show your work in a code chunk and write the answer below.

< Insert code chunk here >  

> Insert answer here  


### 1.12.

One of the individuals in the data set has a brain weight of 1334 grams and a head size of 3903 cm^3^. Calculate the residual for the data point. Show your work in the code chunk. What does that value mean for the brain weight in context?

< Insert code chunk here >  

> Insert answer here  


### 1.13.

Does the linear model with head size explain much of the variability in brain weight of healthy adults? How much variability does it explain? Does that seem like a good model to use for predictions (evaluate the strength of the model fit)?   

< Insert code chunk here >  

> Insert answer here 



## Scenario 2: Agricultural Intensity   

Subsistence farming refers to small agricultural communities that consume most of their crop production. These farms use systems that are extensive, meaning they produce a relatively small amount of crops from a large parcel of land with minimum attention and expense. Naturally, extensive agricultural systems can’t support high population densities because of their relatively low production. Therefore, an increase in population is suspected to be a key factor that forces a shift from extensive to intensive systems of agriculture. The intensity of an agricultural system is defined by the frequency with which a parcel of land is cultivated or is fallow (unplanted) in a crop-fallow cycle. For example a 1 year crop and 0 year fallow cycle would have an agriculture intensity of 100%. While a 1 year crop and 1 year fallow would have an agricultural intensity of 50% and considered less intense than the former example. Researchers are interested in learning about the relationship between agricultural intensity and population density. They gathered data from randomly selected subsistence farms; they did not narrow their focus to farms of any particular crop, but did limit the subsistence farms to ones in tropical environments. In each of these locations, the agricultural intensity, population density and other variables were recorded. Here population density (in km^2^) is the ratio of the population to the total area available to it for farming. 
You can find the data in `ag-intensity.csv`


### 2.1.

Name the response and explanatory variables of interest and, for each, state the type of variable (quantitative or qualitative).

> Response:

> Explanatory:


### 2.2.

TRUE or FALSE? We could generalize the results of this study to all tropical subsistence farms. Bold your answer.

TRUE or FALSE? We could determine causality from the results of this study. Bold your answer.


### 2.3.

Explanatory Data Analysis: Insert a code chunk below to create an appropriate graphic and calculate any appropriate summary statistics.

< Insert code chunk here >  


### 2.4.

What is the simplest form (linear, nonlinear, etc) of the relationship between agricultural intensity and population density?

> Insert answer here  


### 2.5.

Is it appropriate to interpret the calculated correlation coefficient or create a linear model for these data?

> Insert answer here  



